config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'restaurants#index'
  resource :user, only: %i[edit update]
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :restaurants, only: %i[index] do
    resources :products, only: %i[index]
  end
  resource :carts, only: %i[edit update]
  resources :order_items
  resources :personal_orders
  resources :favorite_products, only: %i[index create destroy]

  namespace :admin do
    resources :restaurants, only: %i[new create edit update destroy] do
      resources :products, only: %i[new create edit update destroy]
    end

    resources :users

    resources :personal_orders do
      resources :order_items, only: %i[update destroy]
    end

    resources :company_orders
    resource :carts, only: %i[edit update]
  end
end

app/controllers/admin/carts_controller.rb
# frozen_string_literal: true

module Admin
  class CartsController < ApplicationController
    include Authentication
    include Admin::Concerns::AdminAuthentication

    before_action :no_authentication
    before_action :check_admin
  
    def edit
      @company_order = CompanyOrder.find_by(status: 'in progress')
      if params[:focus] == 'restaurant'
        @restaurant_order_items = OrderItem.ordered_by_restaurant
        @grouped_order_items_by_restaurant = @restaurant_order_items.group_by do |order_item|
          order_item.product.restaurant
        end

        @restaurant_total_prices = {}
        @grouped_by_product = {}
        @total_quantity = {}
        @total_price = {}
        @order_item_name = {}
        @order_item_unit_price = {}

        @grouped_order_items_by_restaurant.each do |restaurant, order_items|
          @restaurant_total_prices[restaurant] = order_items.map(&:total_price).sum
          @grouped_by_product[restaurant] = order_items.group_by(&:product_id)
          @grouped_by_product[restaurant].each do |product_id, items|
            @total_quantity[product_id] = items.map(&:quantity).sum
            @total_price[product_id] = items.map(&:total_price).sum
            @order_item_name[product_id] = items.first.name
            @order_item_unit_price[product_id] = items.first.unit_price
          end
        end
      end

      return unless @company_order.nil?

      flash[:warning] = 'Company cart is empty'
      redirect_to root_path
    end

    def update
      @company_order = CompanyOrder.find_by(status: 'in progress')
      @company_order.update(status: 'confirmed')
      redirect_to restaurants_path
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  include Authentication
  
  before_action :no_authentication
  
  def edit
    @order_items = current_order.order_items
  end

  def update
    @company_orders = CompanyOrder.all
    last_order = @company_orders.last
    @company_order = if last_order&.status == 'in progress'
                       last_order
                     else
                       CompanyOrder.create
                     end

    current_order.update(company_order_id: @company_order.id, status: 'confirmed')
    current_order.company_order.save
    session.delete(:personal_order_id)
    redirect_to restaurants_path
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/admin/carts/edit.html.erb
<div class="container-fluid">
  <div class="row">
     <div class="col-md-2">
      <%= form_with(url: edit_admin_carts_path, method: 'get') do |form| %>
       
          <p class="fw-bold">Sort by</p>

          <p><%= form.radio_button :focus, 'personal_order', checked: params[:focus] == 'personal_order', onchange: 'this.form.submit();' %> 
          <%= form.label :focus, 'personal orders'%></p>
     
          <p><%= form.radio_button :focus, 'restaurant', checked: params[:focus] == 'restaurant', onchange: 'this.form.submit();' %> 
          <%= form.label :focus, 'restaurants'%></p>
          
      <%end%>
    </div>

    <div class="col-md-10">
      <% if params[:focus] == 'restaurant' %>
        <% @grouped_order_items_by_restaurant.each do |restaurant, order_items| %>
          <div class="card border border-success rounded-0 border-top-0">
            <div class="card-body">
              <p class="fw-bold"><%= restaurant.name %></p> 
              <table class="table">
                <thead>
                  <tr>
                    <th class="w-25"> Product</th>
                    <th class="w-10 text-center">Unit price</th>
                    <th class="w-10 text-center">Quantity</th>
                    <th class="w-10 text-end">Price</th>
                  </tr>
                </thead>
                                 
                <tbody>
                  <% @grouped_by_product[restaurant].each do |product_id, items| %>                           
                    <tr>
                      <td class="w-25"><%= @order_item_name[product_id] %></td>
                      <td class="w-10 text-center"><%= @order_item_unit_price[product_id] %></td>
                      <td class="w-10 text-center"><%= @total_quantity[product_id] %></td> 
                      <td class="w-10 text-end"><%= @total_price[product_id] %></td>
                    </tr>                    
                  <% end %>
                </tbody>
              </table>
              <p class="text-end fw-bold fs-6 mb-0">Total price: <%= @restaurant_total_prices[restaurant]%></p>
            </div>
          </div>
        <% end %>
        <p class="text-end fw-bold fs-6 mb-5"> Total company price: <%= @company_order.company_price%></p>
      <%else%>
        <% @company_order.personal_orders.each do |personal_order|%>
          <div class="card border border-success rounded-0 border-top-0">
            <div class="card-body">
              <p><%= personal_order.user.phone_number%> 
                <%= personal_order.user.name%> 
                <%= personal_order.user.surname%> </p> 
              <table class="table">
                <thead>
                  <tr>
                    <th class="w-25">Product</th>
                    <th class="w-25">Restaurant</th>
                    <th class="w-10">Unit price</th>
                    <th class="w-10">Quantity</th>
                    <th class="w-10"colspan="1"></th>        
                    <th class="w-10 text-end">Price</th>
                  </tr>
                </thead>
                <tbody>
                  <% personal_order.order_items.each do |order_item|%>
                    <tr>
                      <td class="w-25"><%= order_item.name%></td>
                      <td class="w-25"><%= order_item.product.restaurant.name%></td>
                      <td class="w-10"><%= order_item.unit_price%></td>
                      <td class="w-10">
                        <%= form_with model: [:admin, personal_order, order_item] do |form| %>
                          <%= form.hidden_field :product_id, value: order_item.product.id %> 
                          <%= form.number_field :quantity, in: 1.0..20.0, step: 1, value: order_item.quantity %>
                          <%= form.submit "Update", class: 'btn bg-success-subtle rounded-0' %>
                        <%end%>
                      </td>
                      <td class="w-10"><%= link_to "Destroy", admin_personal_order_order_item_path(personal_order, order_item), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                                        }, class: 'btn bg-success-subtle rounded-0' %></td>
            
                      <td class="w-10 text-end"><%= order_item.total_price%></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>            
              <p class="text-end fw-bold fs-6 mb-0">Total price: <%= personal_order.total_price%></p> 
            </div>
          </div>
        <% end %>    
        <p class="text-end fw-bold fs-6 mb-0"> Total company price: <%= @company_order.company_price%></p> 
        <p> <%= button_to 'Confirm the order', admin_carts_path, method: :patch, class: 'btn bg-success rounded-0 my-2' %> </p>
      <%end%>
    </div>
  </div>
</div>


    