config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'restaurants#index'
  resource :user, only: %i[edit update]
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :restaurants, only: %i[index] do
    resources :products, only: %i[index]
  end
  resource :carts, only: %i[edit update]
  resources :order_items
  resources :personal_orders
  resources :favorite_products, only: %i[index create destroy]

  namespace :admin do
    resources :restaurants, only: %i[new create edit update destroy] do
      resources :products, only: %i[new create edit update destroy]
    end

    resources :users

    resources :personal_orders do
      resources :order_items, only: %i[update destroy]
    end

    resources :company_orders
    resource :carts, only: %i[edit update]
  end
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/admin/restaurants_controller.rb
# frozen_string_literal: true

module Admin
  class RestaurantsController < ApplicationController
    include Authentication
    include Admin::Concerns::AdminAuthentication

    before_action :no_authentication
    before_action :check_admin

    def new
      @restaurant = Restaurant.new
    end

    def create
      create_restaurant
      if @restaurant.valid?
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @restaurant = Restaurant.find(params[:id])
    end

    def update
      @restaurant = Restaurant.find(params[:id])
      if @restaurant.update(restaurant_params)
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @restaurant = Restaurant.find(params[:id])
      @restaurant.destroy
      redirect_to root_path
    end

    private

    def create_restaurant
      @restaurant = Restaurant.create(restaurant_params)
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :phone_number, :address)
    end
  end
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/restaurants/index.html.erb
<div class="container-fluid"> 
  <div class="row mt-4">
    <% @restaurants.each do |restaurant| %>
      <div class="col-lg-4 col-md-6 col-12 mb-4">
        <div class="card border border-success rounded-0 h-100">
          <div class="card-body px-5">
            <h5><%= link_to restaurant.name, restaurant_products_path(restaurant), class: 'nav-link ' %></h5>
            <p>Phone number: <%= restaurant.phone_number %></p>
            <p>Address: <%= restaurant.address %></p>

            <% if current_user.present? && current_user.status?%>
              <p><%= link_to 'Edit restaurant', edit_admin_restaurant_path(restaurant), class: 'btn bg-success-subtle rounded-0' %>
              <%= link_to 'Delete restaurant', admin_restaurant_path(restaurant), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"}, class: 'btn bg-success-subtle rounded-0' %> </p>
            <% end %>                             
          </div>
        </div>
      </div>
    <% end %>   
  </div>
</div>