config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'restaurants#index'
  resource :user, only: %i[edit update]
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :restaurants, only: %i[index] do
    resources :products, only: %i[index]
  end
  resource :carts, only: %i[edit update]
  resources :order_items
  resources :personal_orders
  resources :favorite_products, only: %i[index create destroy]

  namespace :admin do
    resources :restaurants, only: %i[new create edit update destroy] do
      resources :products, only: %i[new create edit update destroy]
    end

    resources :users

    resources :personal_orders do
      resources :order_items, only: %i[update destroy]
    end

    resources :company_orders
    resource :carts, only: %i[edit update]
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
  has_and_belongs_to_many :users
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < ApplicationController
    include Authentication
    include Admin::Concerns::AdminAuthentication

    before_action :no_authentication
    before_action :check_admin

    def index
      @restaurant = Restaurant.find(params[:restaurant_id])
      @products = @restaurant.products
      @order_items = current_order.order_items.new if current_user.present?
    end

    def new
      @restaurant = Restaurant.find(params[:restaurant_id])
      @product = @restaurant.products.new
    end

    def create
      create_product
      if @product.valid?
        redirect_to restaurant_products_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @restaurant = Restaurant.find(params[:restaurant_id])
      @product = @restaurant.products.find(params[:id])
    end

    def update
      @restaurant = Restaurant.find(params[:restaurant_id])
      @product = @restaurant.products.find(params[:id])
      if @product.update(product_params)
        redirect_to restaurant_products_path
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @restaurant = Restaurant.find(params[:restaurant_id])
      @product = @restaurant.products.find(params[:id])

      @company_order = CompanyOrder.find_by(status: 'in progress') 
      if @company_order.present?       
        @personal_orders = @company_order.personal_orders
        @personal_orders.each do |personal_order|
          personal_order.order_items.where(product_id: @product.id).destroy_all
          personal_order.save
        end
        @company_order.save
      end

      @company_order = CompanyOrder.find_by(status: 'confirmed')  
      if @company_order.present?    
        @personal_orders = @company_order.personal_orders
        @personal_orders.each do |personal_order|
          personal_order.order_items.where(product_id: @product.id).each do |order_item|
            order_item.update(product_id: 5)
          end
        end
      end
        
      @product.destroy
      redirect_to restaurant_products_path(@restaurant)
    end

    private

    def create_product
      @restaurant = Restaurant.find(params[:restaurant_id])
      @product = @restaurant.products.create(product_params)
    end

    def product_params
      params.require(:product).permit(:name, :price)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @products = @restaurant.products
    @order_items = current_order.order_items.new if current_user.present?
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/index.html.erb
<div class="container-fluid">
  <h4><%= @restaurant.name %></h4>

  <% if current_user.present? && current_user.status? %>
    <p><%= link_to 'New item', new_admin_restaurant_product_path(@restaurant), class: 'btn bg-success-subtle rounded-0' %></p>
  <% end %>

  <% unless current_user.present? %>
    <%= link_to "Sign up to add to cart", new_user_path, class: 'btn bg-success rounded-0' %> 
    <%= link_to "Log in to add to cart", new_session_path, class: 'btn bg-success rounded-0' %>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th class="w-25">Name</th>
        <th class="w-25">Price</th>
        <% if current_user.present? %>
          <th class="w-25">Quantity</th>
          <th class="w-10" colspan="1"></th>
          <% if current_user.status? %>
            <th class="w-10" colspan="2"></th>
          <% end %>  
        <% end %>        
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td class="w-25"><%= product.name %></td>
          <td class="w-25"><%= product.price %></td>
          <% if current_user.present? %>
            <td class="w-25"><%= form_with model: @order_items do |form| %>
                <%= form.hidden_field :product_id, value: product.id %> 
                <%= form.number_field :quantity, in: 1.0..50.0, step: 1, value: 1 %>          
                <%= form.submit "Add to cart", class: 'btn bg-success rounded-0' %>
                <% end %>
            </td>
            
            <% if current_user.products.include?(product) %>
			        <td class="w-10 text-end">
                <%= button_to favorite_product_path(product), method: :delete, class: 'btn bg-transparent rounded-0' do %>
                  <i class="fas fa-heart text-success"></i>
                <% end %>
              </td>             
            <% else %>
              <td class="w-10 text-end">
                <%= button_to favorite_products_path, method: 'post', params: { product_id: product.id }, class: 'btn btn-link text-success' do %>
                  <i class="far fa-heart"></i>
                <% end %>
              </td>
            <% end %>          
          <% end %>  

          <% if current_user.present? && current_user.status? %>
            <td class="w-10"><%= link_to 'Edit item', edit_admin_restaurant_product_path(@restaurant, product), class: 'btn bg-success-subtle rounded-0' %></td>
            <td class="w-10"><%= link_to 'Delete item', admin_restaurant_product_path(@restaurant, product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn bg-success-subtle rounded-0' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>