config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'restaurants#index'
  resource :user, only: %i[edit update]
  resources :users, only: %i[new create]
  resource :session, only: %i[new create destroy]
  resources :restaurants, only: %i[index] do
    resources :products, only: %i[index]
  end
  resource :carts, only: %i[edit update]
  resources :order_items
  resources :personal_orders
  resources :favorite_products, only: %i[index create destroy]

  namespace :admin do
    resources :restaurants, only: %i[new create edit update destroy] do
      resources :products, only: %i[new create edit update destroy]
    end

    resources :users

    resources :personal_orders do
      resources :order_items, only: %i[update destroy]
    end

    resources :company_orders
    resource :carts, only: %i[edit update]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company_order.rb
# frozen_string_literal: true

class CompanyOrder < ApplicationRecord
  has_many :personal_orders, dependent: :destroy

  before_save :update_company_price

  VALID_STATUS = ['in progress', 'confirmed'].freeze
  validates :status, inclusion: { in: VALID_STATUS }

  scope :company_order_desc, -> { order(updated_at: :desc) }

  def update_company_price
    self.company_price = personal_orders.sum(:total_price)
  end
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :personal_order
  belongs_to :product

  before_validation :update_attributes_from_product

  scope :ordered_by_restaurant, lambda {
                                  joins(personal_order: :company_order)
                                    .where(company_orders: { status: 'in progress' })
                                    .includes(product: :restaurant)
                                    .order('restaurants.name')
                                }

  private

  def update_attributes_from_product
    self.name = product.name if new_record?
    self.unit_price = product.price if new_record?
    self.total_price = unit_price * quantity
  end
end

app/models/personal_order.rb
# frozen_string_literal: true

class PersonalOrder < ApplicationRecord
  belongs_to :company_order, optional: true
  belongs_to :user
  has_many :order_items, dependent: :destroy

  before_save :update_total_price

  VALID_STATUS = ['in progress', 'confirmed'].freeze
  validates :status, inclusion: { in: VALID_STATUS }

  scope :personal_order_desc, -> { order(updated_at: :desc) }

  def update_total_price
    self.total_price = order_items.map { |order_item| order_item.quantity * order_item.unit_price }.sum
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :restaurant
  has_many :order_items
  has_and_belongs_to_many :users
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :personal_orders, dependent: :destroy
  has_and_belongs_to_many :products

  before_save :capitalize_name, :capitalize_surname

  validates :phone_number, presence: true, uniqueness: true, format: { with: /\A\+\d+\z/ }, length: { is: 13 }
  validates :password, confirmation: true, length: { minimum: 6, maximum: 70 }, if: :password_validation_required?
  validates :name, presence: true, length: { minimum: 2, maximum: 40 }
  validates :surname, presence: true, length: { minimum: 2, maximum: 40 }

  private

  def capitalize_name
    self.name = name.capitalize
  end

  def capitalize_surname
    self.surname = surname.capitalize
  end  

  def password_validation_required?
    new_record? || password_digest_changed?
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  include Authentication
  
  before_action :no_authentication
  
  def edit
    @order_items = current_order.order_items
  end

  def update
    @company_orders = CompanyOrder.all
    last_order = @company_orders.last
    @company_order = if last_order&.status == 'in progress'
                       last_order
                     else
                       CompanyOrder.create
                     end

    current_order.update(company_order_id: @company_order.id, status: 'confirmed')
    current_order.company_order.save
    session.delete(:personal_order_id)
    redirect_to restaurants_path
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @products = @restaurant.products
    @order_items = current_order.order_items.new if current_user.present?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  include Authentication

  before_action :authentication, only: %i[new create]
  before_action :no_authentication, only: %i[destroy]

  def new; end

  def create
    user_params = params.require(:session)
    user = User.find_by(phone_number: user_params[:phone_number])&.authenticate(user_params[:password])
    if user.present?
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:personal_order_id)
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Authentication

  before_action :authentication, only: %i[new create]
  before_action :no_authentication, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    create_user
    session[:user_id] = @user.id
    if @user.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def create_user
    @user = User.create(user_params)
  end

  def user_params
    params.require(:user).permit(:name, :surname, :phone_number, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/company_orders_helper.rb
# frozen_string_literal: true

module CompanyOrdersHelper
end

app/helpers/order_items_helper.rb
# frozen_string_literal: true

module OrderItemsHelper
end

app/helpers/personal_orders_helper.rb
# frozen_string_literal: true

module PersonalOrdersHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-success-subtle border border-success sticky-top">
  <div class="container-fluid bg-success border border-success rounded-left p-2 d-flex justify-content-between align-items-center">
    <ul class="navbar-nav">
      <li class="nav-item"> <%= link_to "Restaurants", restaurants_path, class: "nav-link" %> </li> 
        <% if current_user.present? %>
        <% if current_user.status? %>
          <li class="nav-item"> <%= link_to "New restaurant", new_admin_restaurant_path, class: "nav-link" %> </li>
          <li class="nav-item"> <%= link_to "Users", admin_users_path, class: "nav-link" %> </li>
          <li class="nav-item"> <%= link_to "New user", new_admin_user_path, class: "nav-link" %> </li>
          <li class="nav-item"> <%= link_to "Company orders", admin_company_orders_path, class: "nav-link" %> </li> 
        <% end %>
      <% end %>
    </ul>
    <ul class="navbar-nav">
    <% if current_user.present? %>
      <% if current_user.status? %>
        <li class="nav-item"><%= link_to "Company cart", edit_admin_carts_path, class: "nav-link" %> </li> 
      <% end %>    
      <li class="nav-item"><%= link_to "Cart", edit_carts_path, class: "nav-link" %> </li> 
      <li class="nav-item">
        <%= link_to favorite_products_path, class: "nav-link" do %>
          <i class="far fa-heart"></i>
        <% end %> 
      </li>
      <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle px-5" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "#{current_user.name}" %>
          </a>
          <ul class="dropdown-menu border border-success">
            <li> <%= link_to "Log out", session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'dropdown-item' %></li>
            <li> <%= link_to "Edit profile", edit_user_path, class: 'dropdown-item' %></li>
            <li><%= link_to "My orders", personal_orders_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
       
      <% else %>
    <li class="nav-item"><%= link_to "Sign up", new_user_path, class: "nav-link" %> </li> 
    <li class="nav-item"><%= link_to "Log in", new_session_path, class: "nav-link" %> </li> 
     <% end %>
     </ul>
  </div>
</nav>


<% if flash[:success].present? %>
     <div class="alert alert-success"><%= flash[:success]%></div>
    <% elsif flash[:warning].present? %> 
     <div class="alert alert-danger"><%= flash[:warning] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>